### ISSUE TITLE
Move to ckan organization

### ISSUE THREAD

**Issue by rufuspollock** [okfn/ckanclient-deprecated#39]
@kindly @seanh wdyt?

Also should we not attempt to merge this with ckanapi (or deprecate this in favour of ckanapi?)

**Comment by seanh** [comment]
This is deprecated in favor of ckanapi

**Comment by rufuspollock** [comment]
@seanh great! I'll mark it as such.

**Comment by seanh** [comment]
Cheers @rgrp
